DROP DATABASE IF EXISTS pokemon;
CREATE DATABASE pokemon;
USE pokemon;

CREATE TABLE pokemon (
	id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(25),
    generacion INT
);

CREATE TABLE tipo (
	id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(20)
);

CREATE TABLE pokemon_tipos (
	id_pokemon INT,
	id_tipo INT,
	CONSTRAINT pk_pokemon_tipo PRIMARY KEY (id_pokemon, id_tipo),
	CONSTRAINT fk_pokemon FOREIGN KEY (id_pokemon) REFERENCES pokemon(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	CONSTRAINT fk_tipo FOREIGN KEY (id_tipo) REFERENCES tipo(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

INSERT INTO tipo (nombre) VALUES
	("Planta"),
    ("Fuego"),
    ("Agua"),
    ("Bicho"),
    ("Volador"),
    ("Normal"),
    ("Eléctrico"),
    ("Tierra"),
    ("Roca"),
    ("Veneno"),
    ("Fantasma"),
    ("Hielo"),
    ("Psíquico"),
    ("Lucha"),
    ("Dragón"),
    ("Siniestro"),
    ("Acero"),
    ("Hada");
    
INSERT INTO pokemon (nombre, generacion) VALUES
	("Bulbasaur",1),
	("Ivysaur",1),
	("Venusaur",1),
	("Charmander",1),
	("Charmeleon",1),
	("Charizard",1),
	("Squirtle",1),
	("Wartortle",1),
	("Blastoise",1),
	("Caterpie",1),
	("Metapod",1),
	("Butterfree",1),
	("Weedle",1),
	("Kakuna",1),
	("Beedrill",1),
	("Pidgey",1),
	("Pidgeotto",1),
	("Pidgeot",1),
	("Rattata",1),
	("Raticate",1),
	("Spearow",1),
	("Fearow",1),
	("Ekans",1),
	("Arbok",1),
	("Pikachu",1),
	("Raichu",1),
	("Sandshrew",1),
	("Sandslash",1),
	("Nidoran♀",1),
	("Nidorina",1),
	("Nidoqueen",1),
	("Nidoran♂",1),
	("Nidorino",1),
	("Nidoking",1),
	("Clefairy",1),
	("Clefable",1),
	("Vulpix",1),
	("Ninetales",1),
	("Jigglypuff",1),
	("Wigglytuff",1),
	("Zubat",1),
	("Golbat",1),
	("Oddish",1),
	("Gloom",1),
	("Vileplume",1),
	("Paras",1),
	("Parasect",1),
	("Venonat",1),
	("Venomoth",1),
	("Diglett",1),
	("Dugtrio",1),
	("Meowth",1),
	("Persian",1),
	("Psyduck",1),
	("Golduck",1),
	("Mankey",1),
	("Primeape",1),
	("Growlithe",1),
	("Arcanine",1),
	("Poliwag",1),
	("Poliwhirl",1),
	("Poliwrath",1),
	("Abra",1),
	("Kadabra",1),
	("Alakazam",1),
	("Machop",1),
	("Machoke",1),
	("Machamp",1),
	("Bellsprout",1),
	("Weepinbell",1),
	("Victreebel",1),
	("Tentacool",1),
	("Tentacruel",1),
	("Geodude",1),
	("Graveler",1),
	("Golem",1),
	("Ponyta",1),
	("Rapidash",1),
	("Slowpoke",1),
	("Slowbro",1),
	("Magnemite",1),
	("Magneton",1),
	("Farfetch'd",1),
	("Doduo",1),
	("Dodrio",1),
	("Seel",1),
	("Dewgong",1),
	("Grimer",1),
	("Muk",1),
	("Shellder",1),
	("Cloyster",1),
	("Gastly",1),
	("Haunter",1),
	("Gengar",1),
	("Onix",1),
	("Drowzee",1),
	("Hypno",1),
	("Krabby",1),
	("Kingler",1),
	("Voltorb",1),
	("Electrode",1),
	("Exeggcute",1),
	("Exeggutor",1),
	("Cubone",1),
	("Marowak",1),
	("Hitmonlee",1),
	("Hitmonchan",1),
	("Lickitung",1),
	("Koffing",1),
	("Weezing",1),
	("Rhyhorn",1),
	("Rhydon",1),
	("Chansey",1),
	("Tangela",1),
	("Kangaskhan",1),
	("Horsea",1),
	("Seadra",1),
	("Goldeen",1),
	("Seaking",1),
	("Staryu",1),
	("Starmie",1),
	("Mr. Mime",1),
	("Scyther",1),
	("Jynx",1),
	("Electabuzz",1),
	("Magmar",1),
	("Pinsir",1),
	("Tauros",1),
	("Magikarp",1),
	("Gyarados",1),
	("Lapras",1),
	("Ditto",1),
	("Eevee",1),
	("Vaporeon",1),
	("Jolteon",1),
	("Flareon",1),
	("Porygon",1),
	("Omanyte",1),
	("Omastar",1),
	("Kabuto",1),
	("Kabutops",1),
	("Aerodactyl",1),
	("Snorlax",1),
	("Articuno",1),
	("Zapdos",1),
	("Moltres",1),
	("Dratini",1),
	("Dragonair",1),
	("Dragonite",1),
	("Mewtwo",1),
	("Mew",1),
	("Chikorita",2),
	("Bayleef",2),
	("Meganium",2),
	("Cyndaquil",2),
	("Quilava",2),
	("Typhlosion",2),
	("Totodile",2),
	("Croconaw",2),
	("Feraligatr",2),
	("Sentret",2),
	("Furret",2),
	("Hoothoot",2),
	("Noctowl",2),
	("Ledyba",2),
	("Ledian",2),
	("Spinarak",2),
	("Ariados",2),
	("Crobat",2),
	("Chinchou",2),
	("Lanturn",2),
	("Pichu",2),
	("Cleffa",2),
	("Igglybuff",2),
	("Togepi",2),
	("Togetic",2),
	("Natu",2),
	("Xatu",2),
	("Mareep",2),
	("Flaaffy",2),
	("Ampharos",2),
	("Bellossom",2),
	("Marill",2),
	("Azumarill",2),
	("Sudowoodo",2),
	("Politoed",2),
	("Hoppip",2),
	("Skiploom",2),
	("Jumpluff",2),
	("Aipom",2),
	("Sunkern",2),
	("Sunflora",2),
	("Yanma",2),
	("Wooper",2),
	("Quagsire",2),
	("Espeon",2),
	("Umbreon",2),
	("Murkrow",2),
	("Slowking",2),
	("Misdreavus",2),
	("Unown",2),
	("Wobbuffet",2),
	("Girafarig",2),
	("Pineco",2),
	("Forretress",2),
	("Dunsparce",2),
	("Gligar",2),
	("Steelix",2),
	("Snubbull",2),
	("Granbull",2),
	("Qwilfish",2),
	("Scizor",2),
	("Shuckle",2),
	("Heracross",2),
	("Sneasel",2),
	("Teddiursa",2),
	("Ursaring",2),
	("Slugma",2),
	("Magcargo",2),
	("Swinub",2),
	("Piloswine",2),
	("Corsola",2),
	("Remoraid",2),
	("Octillery",2),
	("Delibird",2),
	("Mantine",2),
	("Skarmory",2),
	("Houndour",2),
	("Houndoom",2),
	("Kingdra",2),
	("Phanpy",2),
	("Donphan",2),
	("Porygon2",2),
	("Stantler",2),
	("Smeargle",2),
	("Tyrogue",2),
	("Hitmontop",2),
	("Smoochum",2),
	("Elekid",2),
	("Magby",2),
	("Miltank",2),
	("Blissey",2),
	("Raikou",2),
	("Entei",2),
	("Suicune",2),
	("Larvitar",2),
	("Pupitar",2),
	("Tyranitar",2),
	("Lugia",2),
	("Ho-Oh",2),
	("Celebi",2),
	("Treecko",3),
	("Grovyle",3),
	("Sceptile",3),
	("Torchic",3),
	("Combusken",3),
	("Blaziken",3),
	("Mudkip",3),
	("Marshtomp",3),
	("Swampert",3),
	("Poochyena",3),
	("Mightyena",3),
	("Zigzagoon",3),
	("Linoone",3),
	("Wurmple",3),
	("Silcoon",3),
	("Beautifly",3),
	("Cascoon",3),
	("Dustox",3),
	("Lotad",3),
	("Lombre",3),
	("Ludicolo",3),
	("Seedot",3),
	("Nuzleaf",3),
	("Shiftry",3),
	("Taillow",3),
	("Swellow",3),
	("Wingull",3),
	("Pelipper",3),
	("Ralts",3),
	("Kirlia",3),
	("Gardevoir",3),
	("Surskit",3),
	("Masquerain",3),
	("Shroomish",3),
	("Breloom",3),
	("Slakoth",3),
	("Vigoroth",3),
	("Slaking",3),
	("Nincada",3),
	("Ninjask",3),
	("Shedinja",3),
	("Whismur",3),
	("Loudred",3),
	("Exploud",3),
	("Makuhita",3),
	("Hariyama",3),
	("Azurill",3),	 
	("Nosepass",3),
	("Skitty",3),
	("Delcatty",3),
	("Sableye",3),
	("Mawile",3),	 
	("Aron",3),
	("Lairon",3),
	("Aggron",3),
	("Meditite",3),
	("Medicham",3),
	("Electrike",3),
	("Manectric",3),
	("Plusle",3),
	("Minun",3),
	("Volbeat",3),
	("Illumise",3),
	("Roselia",3),
	("Gulpin",3),
	("Swalot",3),
	("Carvanha",3),
	("Sharpedo",3),
	("Wailmer",3),
	("Wailord",3),
	("Numel",3),
	("Camerupt",3),
	("Torkoal",3),
	("Spoink",3),
	("Grumpig",3),
	("Spinda",3),
	("Trapinch",3),
	("Vibrava",3),
	("Flygon",3),
	("Cacnea",3),
	("Cacturne",3),
	("Swablu",3),
	("Altaria",3),
	("Zangoose",3),
	("Seviper",3),
	("Lunatone",3),
	("Solrock",3),
	("Barboach",3),
	("Whiscash",3),
	("Corphish",3),
	("Crawdaunt",3),
	("Baltoy",3),
	("Claydol",3),
	("Lileep",3),
	("Cradily",3),
	("Anorith",3),
	("Armaldo",3),
	("Feebas",3),
	("Milotic",3),
	("Castform",3),
	("Kecleon",3),
	("Shuppet",3),
	("Banette",3),
	("Duskull",3),
	("Dusclops",3),
	("Tropius",3),
	("Chimecho",3),
	("Absol",3),
	("Wynaut",3),
	("Snorunt",3),
	("Glalie",3),
	("Spheal",3),
	("Sealeo",3),
	("Walrein",3),
	("Clamperl",3),
	("Huntail",3),
	("Gorebyss",3),
	("Relicanth",3),
	("Luvdisc",3),
	("Bagon",3),
	("Shelgon",3),
	("Salamence",3),
	("Beldum",3),
	("Metang",3),
	("Metagross",3),
	("Regirock",3),
	("Regice",3),
	("Registeel",3),
	("Latias",3),
	("Latios",3),
	("Kyogre",3),
	("Groudon",3),
	("Rayquaza",3),
	("Jirachi",3),
	("Deoxys",3),
	("Turtwig",4),
	("Grotle",4),
	("Torterra",4),
	("Chimchar",4),
	("Monferno",4),
	("Infernape",4),
	("Piplup",4),
	("Prinplup",4),
	("Empoleon",4),
	("Starly",4),
	("Staravia",4),
	("Staraptor",4),
	("Bidoof",4),
	("Bibarel",4),
	("Kricketot",4),
	("Kricketune",4),
	("Shinx",4),
	("Luxio",4),
	("Luxray",4),
	("Budew",4),
	("Roserade",4),
	("Cranidos",4),
	("Rampardos",4),
	("Shieldon",4),
	("Bastiodon",4),
	("Burmy",4),
	("Wormadam",4),
	("Mothim",4),
	("Combee",4),
	("Vespiquen",4),
	("Pachirisu",4),
	("Buizel",4),
	("Floatzel",4),
	("Cherubi",4),
	("Cherrim",4),
	("Shellos",4),
	("Gastrodon",4),
	("Ambipom",4),
	("Drifloon",4),
	("Drifblim",4),
	("Buneary",4),
	("Lopunny",4),
	("Mismagius",4),
	("Honchkrow",4),
	("Glameow",4),
	("Purugly",4),
	("Chingling",4),
	("Stunky",4),
	("Skuntank",4),
	("Bronzor",4),
	("Bronzong",4),
	("Bonsly",4),
	("Mime Jr.	 ",4),
	("Happiny",4),
	("Chatot",4),
	("Spiritomb",4),
	("Gible",4),
	("Gabite",4),
	("Garchomp",4),
	("Munchlax",4),
	("Riolu",4),
	("Lucario",4),
	("Hippopotas",4),
	("Hippowdon",4),
	("Skorupi",4),
	("Drapion",4),
	("Croagunk",4),
	("Toxicroak",4),
	("Carnivine",4),
	("Finneon",4),
	("Lumineon",4),
	("Mantyke",4),
	("Snover",4),
	("Abomasnow",4),
	("Weavile",4),
	("Magnezone",4),
	("Lickilicky",4),
	("Rhyperior",4),
	("Tangrowth",4),
	("Electivire",4),
	("Magmortar",4),
	("Togekiss",4),
	("Yanmega",4),
	("Leafeon",4),
	("Glaceon",4),
	("Gliscor",4),
	("Mamoswine",4),
	("Porygon-Z",4),
	("Gallade",4),
	("Probopass",4),
	("Dusknoir",4),
	("Froslass",4),
	("Rotom",4),
	("Uxie",4),
	("Mesprit",4),
	("Azelf",4),
	("Dialga",4),
	("Palkia",4),
	("Heatran",4),
	("Regigigas",4),
	("Giratina",4),
	("Cresselia",4),
	("Phione",4),
	("Manaphy",4),
	("Darkrai",4),
	("Shaymin",4),
	("Arceus",4),
	("Victini",5),
	("Snivy",5),
	("Servine",5),
	("Serperior",5),
	("Tepig",5),
	("Pignite",5),
	("Emboar",5),
	("Oshawott",5),
	("Dewott",5),
	("Samurott",5),
	("Patrat",5),
	("Watchog",5),
	("Lillipup",5),
	("Herdier",5),
	("Stoutland",5),
	("Purrloin",5),
	("Liepard",5),
	("Pansage",5),
	("Simisage",5),
	("Pansear",5),
	("Simisear",5),
	("Panpour",5),
	("Simipour",5),
	("Munna",5),
	("Musharna",5),
	("Pidove",5),
	("Tranquill",5),
	("Unfezant",5),
	("Blitzle",5),
	("Zebstrika",5),
	("Roggenrola",5),
	("Boldore",5),
	("Gigalith",5),
	("Woobat",5),
	("Swoobat",5),
	("Drilbur",5),
	("Excadrill",5),
	("Audino",5),
	("Timburr",5),
	("Gurdurr",5),
	("Conkeldurr",5),
	("Tympole",5),
	("Palpitoad",5),
	("Seismitoad",5),
	("Throh",5),
	("Sawk",5),
	("Sewaddle",5),
	("Swadloon",5),
	("Leavanny",5),
	("Venipede",5),
	("Whirlipede",5),
	("Scolipede",5),
	("Cottonee",5),
	("Whimsicott",5),
	("Petilil",5),
	("Lilligant",5),
	("Basculin",5),
	("Sandile",5),
	("Krokorok",5),
	("Krookodile",5),
	("Darumaka",5),
	("Darmanitan",5),
	("Maractus",5),
	("Dwebble",5),
	("Crustle",5),
	("Scraggy",5),
	("Scrafty",5),
	("Sigilyph",5),
	("Yamask",5),
	("Cofagrigus",5),
	("Tirtouga",5),
	("Carracosta",5),
	("Archen",5),
	("Archeops",5),
	("Trubbish",5),
	("Garbodor",5),
	("Zorua",5),
	("Zoroark",5),
	("Minccino",5),
	("Cinccino",5),
	("Gothita",5),
	("Gothorita",5),
	("Gothitelle",5),
	("Solosis",5),
	("Duosion",5),
	("Reuniclus",5),
	("Ducklett",5),
	("Swanna",5),
	("Vanillite",5),
	("Vanillish",5),
	("Vanilluxe",5),
	("Deerling",5),
	("Sawsbuck",5),
	("Emolga",5),
	("Karrablast",5),
	("Escavalier",5),
	("Foongus",5),
	("Amoonguss",5),
	("Frillish",5),
	("Jellicent",5),
	("Alomomola",5),
	("Joltik",5),
	("Galvantula",5),
	("Ferroseed",5),
	("Ferrothorn",5),
	("Klink",5),
	("Klang",5),
	("Klinklang",5),
	("Tynamo",5),
	("Eelektrik",5),
	("Eelektross",5),
	("Elgyem",5),
	("Beheeyem",5),
	("Litwick",5),
	("Lampent",5),
	("Chandelure",5),
	("Axew",5),
	("Fraxure",5),
	("Haxorus",5),
	("Cubchoo",5),
	("Beartic",5),
	("Cryogonal",5),
	("Shelmet",5),
	("Accelgor",5),
	("Stunfisk",5),
	("Mienfoo",5),
	("Mienshao",5),
	("Druddigon",5),
	("Golett",5),
	("Golurk",5),
	("Pawniard",5),
	("Bisharp",5),
	("Bouffalant",5),
	("Rufflet",5),
	("Braviary",5),
	("Vullaby",5),
	("Mandibuzz",5),
	("Heatmor",5),
	("Durant",5),
	("Deino",5),
	("Zweilous",5),
	("Hydreigon",5),
	("Larvesta",5),
	("Volcarona",5),
	("Cobalion",5),
	("Terrakion",5),
	("Virizion",5),
	("Tornadus",5),
	("Thundurus",5),
	("Reshiram",5),
	("Zekrom",5),
	("Landorus",5),
	("Kyurem",5),
	("Keldeo",5),
	("Meloetta",5),
	("Genesect",5),
	("Chespin",6),
	("Quilladin",6),
	("Chesnaught",6),
	("Fennekin",6),
	("Braixen",6),
	("Delphox",6),
	("Froakie",6),
	("Frogadier",6),
	("Greninja",6),
	("Bunnelby",6),
	("Diggersby",6),
	("Fletchling",6),
	("Fletchinder",6),
	("Talonflame",6),
	("Scatterbug",6),
	("Spewpa",6),
	("Vivillon",6),
	("Litleo",6),
	("Pyroar",6),
	("Flabébé",6),
	("Floette",6),
	("Florges",6),
	("Skiddo",6),
	("Gogoat",6),
	("Pancham",6),
	("Pangoro",6),
	("Furfrou",6),
	("Espurr",6),
	("Meowstic",6),
	("Honedge",6),
	("Doublade",6),
	("Aegislash",6),
	("Spritzee",6),
	("Aromatisse",6),
	("Swirlix",6),
	("Slurpuff",6),
	("Inkay",6),
	("Malamar",6),
	("Binacle",6),
	("Barbaracle",6),
	("Skrelp",6),
	("Dragalge",6),
	("Clauncher",6),
	("Clawitzer",6),
	("Helioptile",6),
	("Heliolisk",6),
	("Tyrunt",6),
	("Tyrantrum",6),
	("Amaura",6),
	("Aurorus",6),
	("Sylveon",6),
	("Hawlucha",6),
	("Dedenne",6),
	("Carbink",6),
	("Goomy",6),
	("Sliggoo",6),
	("Goodra",6),
	("Klefki",6),
	("Phantump",6),
	("Trevenant",6),
	("Pumpkaboo",6),
	("Gourgeist",6),
	("Bergmite",6),
	("Avalugg",6),
	("Noibat",6),
	("Noivern",6),
	("Xerneas",6),
	("Yveltal",6),
	("Zygarde",6),
	("Diancie",6),
	("Hoopa",6),
	("Volcanion",6),
    ("Rowlet",7),
	("Dartrix",7),
	("Decidueye",7),
	("Litten",7),
	("Torracat",7),
	("Incineroar",7),
	("Popplio",7),
	("Brionne",7),
	("Primarina",7),
	("Pikipek",7),
	("Trumbeak",7),
	("Toucannon",7),
	("Yungoos",7),
	("Gumshoos",7),
	("Grubbin",7),
	("Charjabug",7),
	("Vikavolt",7),
	("Crabrawler",7),
	("Crabominable",7),
	("Oricorio",7),
	("Cutiefly",7),
	("Ribombee",7),
	("Rockruff",7),
	("Lycanroc",7),
	("Wishiwashi",7),
	("Mareanie",7),
	("Toxapex",7),
	("Mudbray",7),
	("Mudsdale",7),
	("Dewpider",7),
	("Araquanid",7),
	("Fomantis",7),
	("Lurantis",7),
	("Morelull",7),
	("Shiinotic",7),
	("Salandit",7),
	("Salazzle",7),
	("Stufful",7),
	("Bewear",7),
	("Bounsweet",7),
	("Steenee",7),
	("Tsareena",7),
	("Comfey",7),
	("Oranguru",7),
	("Passimian",7),
	("Wimpod",7),
	("Golisopod",7),
	("Sandygast",7),
	("Palossand",7),
	("Pyukumuku",7),
	("Código Cero",7),
	("Silvally",7),
	("Minior",7),
	("Komala",7),
	("Turtonator",7),
	("Togedemaru",7),
	("Mimikyu",7),
	("Bruxish",7),
	("Drampa",7),
	("Dhelmise",7),
	("Jangmo-o",7),
	("Hakamo-o",7),
	("Kommo-o",7),
	("Tapu Koko",7),
	("Tapu Lele",7),
	("Tapu Bulu",7),
	("Tapu Fini",7),
	("Cosmog",7),
	("Cosmoem",7),
	("Solgaleo",7),
	("Lunala",7),
	("Nihilego",7),
	("Buzzwole",7),
	("Pheromosa",7),
	("Xurkitree",7),
	("Celesteela",7),
	("Kartana",7),
	("Guzzlord",7),
	("Necrozma",7),
	("Magearna",7),
	("Marshadow",7),
	("Poipole",7),
	("Naganadel",7),
	("Stakataka",7),
	("Blacephalon",7),
	("Zeraora",7),
	("Meltan",7),
	("Melmetal",7),
	("Grookey",8),
	("Thwackey",8),
	("Rillaboom",8),
	("Scorbunny",8),
	("Raboot",8),
	("Cinderace",8),
	("Sobble",8),
	("Drizzile",8),
	("Inteleon",8),
	("Skwovet",8),
	("Greedent",8),
	("Rookidee",8),
	("Corvisquire",8),
	("Corviknight",8),
	("Blipbug",8),
	("Dottler",8),
	("Orbeetle",8),
	("Nickit",8),
	("Thievul",8),
	("Gossifleur",8),
	("Eldegoss",8),
	("Wooloo",8),
	("Dubwool",8),
	("Chewtle",8),
	("Drednaw",8),
	("Yamper",8),
	("Boltund",8),
	("Rolycoly",8),
	("Carkol",8),
	("Coalossal",8),
	("Applin",8),
	("Flapple",8),
	("Appletun",8),
	("Silicobra",8),
	("Sandaconda",8),
	("Cramorant",8),
	("Arrokuda",8),
	("Barraskewda",8),
	("Toxel",8),
	("Toxtricity",8),
	("Sizzlipede",8),
	("Centiskorch",8),
	("Clobbopus",8),
	("Grapploct",8),
	("Sinistea",8),
	("Polteageist",8),
	("Hatenna",8),
	("Hattrem",8),
	("Hatterene",8),
	("Impidimp",8),
	("Morgrem",8),
	("Grimmsnarl",8),
	("Obstagoon",8),
	("Perrserker",8),
	("Cursola",8),
	("Sirfetch'd",8),
	("Mr. Rime",8),
	("Runerigus",8),
	("Milcery",8),
	("Alcremie",8),
	("Falinks",8),
	("Pincurchin",8),
	("Snom",8),
	("Frosmoth",8),
	("Stonjourner",8),
	("Eiscue",8),
	("Indeedee",8),
	("Morpeko",8),
	("Cufant",8),
	("Copperajah",8),
	("Dracozolt",8),
	("Arctozolt",8),
	("Dracovish",8),
	("Arctovish",8),
	("Duraludon",8),
	("Dreepy",8),
	("Drakloak",8),
	("Dragapult",8),
	("Zacian",8),
	("Zamazenta",8),
	("Eternatus",8),
	("Kubfu",8),
	("Urshifu",8),
	("Zarude",8),
	("Regieleki",8),
	("Regidrago",8),
	("Glastrier",8),
	("Spectrier",8),
	("Calyrex",8),
	("Wyrdeer",8),
	("Kleavor",8),
	("Ursaluna",8),
	("Basculegion",8),
	("Sneasler",8),
	("Overqwil",8),
	("Enamorus",8),
	("Sprigatito",9),
	("Floragato",9),
	("Meowscarada",9),
	("Fuecoco",9),
	("Crocalor",9),
	("Skeledirge",9),
	("Quaxly",9),
	("Quaxwell",9),
	("Quaquaval",9),
	("Lechonk",9),
	("Oinkologne",9),
	("Tarountula",9),
	("Spidops",9),
	("Nymble",9),
	("Lokix",9),
	("Pawmi",9),
	("Pawmo",9),
	("Pawmot",9),
	("Tandemaus",9),
	("Maushold",9),
	("Fidough",9),
	("Dachsbun",9),
	("Smoliv",9),
	("Dolliv",9),
	("Arboliva",9),
	("Squawkabilly",9),
	("Nacli",9),
	("Naclstack",9),
	("Garganacl",9),
	("Charcadet",9),
	("Armarouge",9),
	("Ceruledge",9),
	("Tadbulb",9),
	("Bellibolt",9),
	("Wattrel",9),
	("Kilowattrel",9),
	("Maschiff",9),
	("Mabosstiff",9),
	("Shroodle",9),
	("Grafaiai",9),
	("Bramblin",9),
	("Brambleghast",9),
	("Toedscool",9),
	("Toedscruel",9),
	("Klawf",9),
	("Capsakid",9),
	("Scovillain",9),
	("Rellor",9),
	("Rabsca",9),
	("Flittle",9),
	("Espathra",9),
	("Tinkatink",9),
	("Tinkatuff",9),
	("Tinkaton",9),
	("Wiglett",9),
	("Wugtrio",9),
	("Bombirdier",9),
	("Finizen",9),
	("Palafin",9),
	("Varoom",9),
	("Revavroom",9),
	("Cyclizar",9),
	("Orthworm",9),
	("Glimmet",9),
	("Glimmora",9),
	("Greavard",9),
	("Houndstone",9),
	("Flamigo",9),
	("Cetoddle",9),
	("Cetitan",9),
	("Veluza",9),
	("Dondozo",9),
	("Tatsugiri",9),
	("Annihilape",9),
	("Clodsire",9),
	("Farigiraf",9),
	("Dudunsparce",9),
	("Kingambit",9),
	("Colmilargo",9),
	("Colagrito",9),
	("Furioseta",9),
	("Melenaleteo",9),
	("Reptalada",9),
	("Pelarena",9),
	("Ferrodada",9),
	("Ferrosaco",9),
	("Ferropalmas",9),
	("Ferrocuello",9),
	("Ferropolilla",9),
	("Ferropúas",9),
	("Frigibax",9),
	("Arctibax",9),
	("Baxcalibur",9),
	("Gimmighoul",9),
	("Gholdengo",9),
	("Wo-Chien",9),
	("Chien-Pao",9),
	("Ting-Lu",9),
	("Chi-Yu",9),
	("Bramaluna",9),
	("Ferropaladín",9),
	("Koraidon",9),
	("Miraidon",9),
	("Ondulagua",9),
	("Ferroverdor",9),
	("Dipplin",9),
	("Poltchageist",9),
	("Sinistcha",9),
	("Okidogi",9),
	("Munkidori",9),
	("Fezandipiti",9),
	("Ogerpon",9),
	("Archaludon",9),
	("Hydrapple",9),
	("Flamariete",9),
	("Electrofuria",9),
	("Ferromole",9),
	("Ferrotesta",9),
	("Terapagos",9),
	("Pecharunt",9);

INSERT INTO pokemon_tipos (id_pokemon, id_tipo) VALUES
	(1,(SELECT id FROM tipo WHERE nombre = 'Planta')),
	(1,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
	(2,(SELECT id FROM tipo WHERE nombre = 'Planta')),
	(2,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
	(3,(SELECT id FROM tipo WHERE nombre = 'Planta')),
	(3,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
	(4,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
	(5,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
	(6,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
	(6,(SELECT id FROM tipo WHERE nombre = 'Volador')),
	(7,(SELECT id FROM tipo WHERE nombre = 'Agua')),
	(8,(SELECT id FROM tipo WHERE nombre = 'Agua')),
	(9,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (10,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (11,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (12,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (12,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (13,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (13,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (14,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (14,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (15,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (15,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (16,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (16,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (17,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (17,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (18,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (18,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (19,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (20,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (21,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (21,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (22,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (22,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (23,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (24,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (25,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (26,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (27,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (28,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (29,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (30,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (31,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (31,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (32,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (33,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (34,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (34,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (35,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (36,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (37,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (38,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (39,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (39,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (40,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (40,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (41,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (41,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (42,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (42,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (43,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (43,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (44,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (44,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (45,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (45,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (46,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (46,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (47,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (47,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (48,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (48,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (49,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (49,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (50,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (51,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (52,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (53,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (54,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (55,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (56,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (57,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (58,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (59,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (60,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (61,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (62,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (62,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (63,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (64,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (65,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (66,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (67,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (68,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (69,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (69,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (70,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (70,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (71,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (71,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (72,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (72,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (73,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (73,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (74,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (74,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (75,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (75,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (76,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (76,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (77,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (78,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (79,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (79,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (80,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (80,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (81,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (81,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (82,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (82,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (83,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (83,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (84,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (84,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (85,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (85,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (86,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (87,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (87,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (88,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (89,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (90,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (91,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (91,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (92,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (92,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (93,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (93,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (94,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (94,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (95,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (95,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (96,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (97,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (98,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (99,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (100,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (101,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (102,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (102,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (103,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (103,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (104,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (105,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (106,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (107,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (108,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (109,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (110,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (111,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (111,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (112,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (112,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (113,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (114,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (115,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (116,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (117,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (118,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (119,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (120,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (121,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (121,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (122,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (122,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (123,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (123,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (124,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (124,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (125,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (126,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (127,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (128,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (129,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (130,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (130,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (131,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (131,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (132,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (133,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (134,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (135,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (136,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (137,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (138,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (138,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (139,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (139,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (140,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (140,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (141,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (141,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (142,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (142,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (143,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (144,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (144,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (145,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (145,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (146,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (146,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (147,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (148,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (149,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (149,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (150,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (151,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (152,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (153,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (154,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (155,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (156,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (157,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (158,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (159,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (160,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (161,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (162,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (163,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (163,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (164,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (164,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (165,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (165,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (166,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (166,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (167,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (167,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (168,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (168,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (169,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (169,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (170,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (170,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (171,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (171,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (172,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (173,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (174,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (174,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (175,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (176,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (176,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (177,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (177,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (178,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (178,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (179,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (180,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (181,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (182,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (183,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (183,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (184,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (184,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (185,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (186,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (187,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (187,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (188,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (188,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (189,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (189,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (190,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (191,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (192,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (193,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (193,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (194,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (194,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (195,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (195,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (196,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (197,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (198,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (198,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (199,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (199,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (200,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (201,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (202,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (203,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (203,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (204,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (205,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (205,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (206,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (207,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (207,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (208,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (208,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (209,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (210,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (211,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (211,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (212,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (212,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (213,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (213,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (214,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (214,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (215,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (215,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (216,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (217,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (218,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (219,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (219,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (220,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (220,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (221,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (221,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (222,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (222,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (223,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (224,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (225,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (225,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (226,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (226,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (227,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (227,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (228,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (228,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (229,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (229,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (230,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (230,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (231,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (232,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (233,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (234,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (235,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (236,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (237,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (238,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (238,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (239,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (240,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (241,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (242,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (243,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (244,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (245,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (246,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (246,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (247,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (247,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (248,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (248,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (249,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (249,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (250,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (250,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (251,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (251,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (252,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (253,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (254,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (254,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (255,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (256,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (256,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (257,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (257,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (258,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (259,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (259,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (260,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (260,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (261,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (262,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (263,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (264,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (265,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (266,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (267,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (267,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (268,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (269,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (269,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (270,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (270,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (271,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (271,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (272,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (272,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (273,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (274,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (274,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (275,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (275,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (276,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (276,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (277,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (277,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (278,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (278,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (279,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (279,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (280,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (281,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (282,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (282,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (283,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (283,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (284,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (284,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (285,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (286,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (286,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (287,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (288,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (289,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (290,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (290,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (291,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (291,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (292,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (292,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (293,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (294,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (295,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (296,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (297,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (298,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (298,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (299,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (300,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (301,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (302,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (302,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (303,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (303,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (304,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (304,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (305,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (305,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (306,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (306,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (307,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (307,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (308,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (308,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (309,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (310,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (311,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (312,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (313,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (314,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (315,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (315,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (316,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (317,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (318,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (318,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (319,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (319,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (320,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (321,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (322,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (322,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (323,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (323,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (324,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (324,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (325,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (326,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (327,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (328,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (329,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (329,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (330,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (330,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (331,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (332,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (332,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (333,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (333,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (334,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (334,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (335,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (336,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (337,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (337,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (338,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (338,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (339,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (339,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (340,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (340,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (341,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (342,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (342,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (343,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (343,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (344,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (344,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (345,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (345,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (346,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (346,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (347,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (347,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (348,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (348,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (349,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (350,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (351,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (352,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (353,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (354,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (355,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (356,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (357,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (357,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (358,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (359,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (360,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (361,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (362,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (363,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (363,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (364,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (364,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (365,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (365,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (366,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (367,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (368,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (369,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (369,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (370,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (371,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (372,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (373,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (373,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (374,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (374,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (375,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (375,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (376,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (376,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (377,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (378,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (379,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (380,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (380,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (381,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (381,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (382,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (383,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (384,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (384,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (385,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (385,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (386,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (387,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (388,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (389,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (389,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (390,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (391,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (391,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (392,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (392,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (393,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (394,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (395,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (395,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (396,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (396,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (397,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (397,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (398,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (398,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (399,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (400,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (400,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (401,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (402,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (403,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (404,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (405,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (406,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (406,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (407,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (407,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (408,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (409,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (410,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (410,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (411,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (411,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (412,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (413,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (413,(SELECT id FROM tipo WHERE nombre = 'Planta')), -- Forma Planta
    (413,(SELECT id FROM tipo WHERE nombre = 'Tierra')), -- Forma Arena
    (413,(SELECT id FROM tipo WHERE nombre = 'Acero')), -- Forma Basura
    (414,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (414,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (415,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (415,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (416,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (416,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (417,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (418,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (419,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (420,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (421,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (421,(SELECT id FROM tipo WHERE nombre = 'Fuego')), -- Forma Sol
    (422,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (423,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (423,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (424,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (425,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (425,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (426,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (426,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (427,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (428,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (429,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (430,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (430,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (431,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (432,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (433,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (434,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (434,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (435,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (435,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (436,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (436,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (437,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (437,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (438,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (439,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (439,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (440,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (441,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (441,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (442,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (442,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (443,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (443,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (444,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (444,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (445,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (445,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (446,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (447,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (448,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (448,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (449,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (450,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (451,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (451,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (452,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (452,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (453,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (453,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (454,(SELECT id FROM tipo WHERE nombre = 'Veneno')),
    (454,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (455,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (456,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (457,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (458,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (458,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (459,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (459,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (460,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (460,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (461,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (461,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (462,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (462,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (463,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (464,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (464,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (465,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (466,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (467,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (468,(SELECT id FROM tipo WHERE nombre = 'Hada')),
    (468,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (469,(SELECT id FROM tipo WHERE nombre = 'Bicho')),
    (469,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (470,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (471,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (472,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (472,(SELECT id FROM tipo WHERE nombre = 'Volador')),
    (473,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (473,(SELECT id FROM tipo WHERE nombre = 'Tierra')),
    (474,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (475,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (475,(SELECT id FROM tipo WHERE nombre = 'Lucha')),
    (476,(SELECT id FROM tipo WHERE nombre = 'Roca')),
    (476,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (477,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (478,(SELECT id FROM tipo WHERE nombre = 'Hielo')),
    (478,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (479,(SELECT id FROM tipo WHERE nombre = 'Eléctrico')),
    (479,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (480,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (481,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (482,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (483,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (483,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (484,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (484,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (485,(SELECT id FROM tipo WHERE nombre = 'Fuego')),
    (485,(SELECT id FROM tipo WHERE nombre = 'Acero')),
    (486,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (487,(SELECT id FROM tipo WHERE nombre = 'Fantasma')),
    (487,(SELECT id FROM tipo WHERE nombre = 'Dragón')),
    (488,(SELECT id FROM tipo WHERE nombre = 'Psíquico')),
    (489,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (490,(SELECT id FROM tipo WHERE nombre = 'Agua')),
    (491,(SELECT id FROM tipo WHERE nombre = 'Siniestro')),
    (492,(SELECT id FROM tipo WHERE nombre = 'Planta')),
    (492,(SELECT id FROM tipo WHERE nombre = 'Volador')), -- Forma Cielo
    (493,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (494,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (495,(SELECT id FROM tipo WHERE nombre = 'Normal')),
    (496,(SELECT id FROM tipo WHERE nombre = 'Normal')),
